version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.2.1
  go: circleci/go@1.5.0


alias:
  - &workdir /home/circleci/build

  - &container_config
    docker:
      - image: circleci/python:3.8.0
    environment: 
      SERVICE_NAME: volatrader
    working_directory: *workdir

  - &setup_remote_docker setup_remote_docker

  - &checkout checkout

  - &install_aws_cli aws-cli/install

  - &configure_aws_cli
    aws-cli/setup:
      aws-region: 'AWS_REGION'
      aws-access-key-id: 'AWS_ACCESS_KEY_ID'
      aws-secret-access-key: 'AWS_SECRET_ACCESS_KEY'

  - &install_go go/install

  - &install_deps
    run:
      name: Installing dependencies
      command: make deps

  - &setup_docker_compose
    run:
      name: Install Docker Compose
      command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

  - &create_env
    run:
      name: Creating prod config.env
      command: chmod +x create_env.sh && sh create_env.sh

  - &unit_test
    run:
      name: Running unit tests
      command: make test

  - &integration_test
    run:
      name: Running integration tests
      command: make ci-integration-tests

  - &build_container
    run:
      name: Building docker container
      command: make docker-build

  - &ecr_login
    run:
      name: Logging into ecr
      command: make ecr-login

  - &tag_image
      run:
        name: Tagging image
        command: docker tag ${SERVICE_NAME}:latest ${ECR_URI}/${SERVICE_NAME}:$(echo $CIRCLE_SHA1 | cut -c -7)

  - &ecr_push_image
    run:
        name: Pushing image to ECR
        command: make ecr-push-image

  - &echo_commit_hash
    run:
        name: Commit sha
        command: echo $CIRCLE_SHA1 | cut -c -7
  
  - &build_image_filters
    filters:
      branches:
        ignore: main

  - &lint_code
    run:
        name: Linting go code
        command: make lint
        

jobs:
  build:
    <<: *container_config
    steps:
        - *setup_docker_compose
        - *setup_remote_docker
        - *configure_aws_cli
        - *checkout
        - *lint_code


workflows:
  version: 2

  build-image:
    jobs:
      - build:
          <<: *build_image_filters
          context: aws-production
